Adding Darkmode to graphiql
graphql/graphiql pull request #2146
Opened 2022-01-21 15:38 UTC by harshitkumar31

Addresses https://github.com/graphql/graphiql/issues/129
<img width="1676" alt="Screenshot 2022-01-21 at 8 58 12 PM" src="https://user-images.githubusercontent.com/15359962/150555303-f668f8f3-699a-4835-81c3-95f25faa20a2.png">

2022-02-02 17:31 UTC, acao commented
also, can you add it to `GraphiQLProps` and document the property?  currently, it's only been added to `GraphiQLState`

2022-02-02 17:42 UTC, acao requested changes

2022-02-02 17:42 UTC, acao commented on packages/graphiql/src/css/app.css
> +}
newline please!

2022-02-02 17:42 UTC, acao commented on packages/graphiql/src/components/GraphiQL.tsx
> +      <>
I don't think we need to wrap the entire output in a fragment. I suspect this is why there is such a huge diff in this render!? would like to simplify this diff so I can understand these changes better

2022-02-02 17:42 UTC, acao commented on packages/graphiql/src/components/GraphiQL.tsx
> +  darkMode: boolean;
do we want to provide a `defaultTheme`: "light" | "dark" prop so that implementers can default to dark mode for their users?

2022-02-02 17:42 UTC, acao commented
looks great overall! again, thanks so much for this

2022-02-02 21:36 UTC, acao commented
damn, that was fast!

2022-02-02 23:49 UTC, acao commented
Actually you know what - we might need to re-evaluate this strategy for 1.0 because it will invert `GraphiQL.Logo` which is still supported until 2.0, as well as images in markdown docs. I didn't realize `filter` would work on images! Can we use a different strategy?

2022-02-03 19:27 UTC, harshitkumar31 commented
@acao , Added a style to ensure images are inverted.
For the lack of a better example, I added an image inline to test it. This should address your concern w.r.t `GraphiQL.Logo`
<img width="1680" alt="Screenshot 2022-02-04 at 12 53 17 AM" src="https://user-images.githubusercontent.com/15359962/152414668-b616706d-fb09-4529-846e-b79d73ec4328.png">

2022-02-03 20:16 UTC, acao commented
thank you!

2022-02-03 20:27 UTC, acao commented
Hmmm... doc explorer font colors... I don't know... hmm!

2022-02-05 04:51 UTC, pedroleinar commented
Hi, how you doing ? what should be changed? Can I help you?

2022-02-05 06:47 UTC, acao commented
I have been working and sleeping? it is 7am here lol.

To be clear, I don’t think the css filter approach will work. Someone tried this PR years ago and I asked them to just override the css classes the more conventional way and they abandoned the PR.

This approach makes all the colors look weird, and now the doc explorer fails accessibility tests if dark mode is enabled because of the color contrast

There is a css file someone posted on gist in that thread that should be fine with some tweaking, but make sure it works for query history as well

in the new graphiql rfc as you can see we dont use CSS files, we use theme ui & emotion css, so you don’t have to worry about this working in 2.0 because we will use a different technique for accessing dark/light/solarized and other filtered theme modes, as well as user theme selection. User just provides a set of theme object literals.  This is why we were waiting for 2.x to do this but no one is working on graphiql or has time

2022-02-06 08:38 UTC, harshitkumar31 commented
I see. I don't have enough cycles or knowledge to implement the suggested changes. I'll close the PR, thanks.

2022-02-06 09:36 UTC, acao commented
Well, you don’t need to close it in my opinion. I am glad to help you with this PR. I appreciate your initiative immensely, and a dark mode would be a great addition to wrap up 1.0

I completely forgot that a major part of this strategy should involve dynamically changing the codemirrir theme as well!

2022-02-06 09:38 UTC, acao commented
It could be that we also get filter: invert() working where the doc explorer items look funky now (try doc search as well). Probably just a few more css selectors is all we need

2022-02-06 09:40 UTC, acao commented
How about I create a new PR with your commit and my changes? That way you get credit for the original approach. I think we can make this work even if you don’t have time to finish. I think this will work out just fine!

2022-02-06 13:37 UTC, harshitkumar31 commented
Sounds good. Thanks @acao

2022-05-09 16:46 UTC, thomasheyenbrock commented
As part of the designs for GraphiQL v2 we'll ship a dedicated dark mode implementation, for updates see #2328. I'm closing this PR in favor of the upcoming dark mode implementation. Thanks anyways! 🙂

2022-05-09 16:46 UTC, closed without merging