Upgrade to ts-node 10.x
graphql/graphiql pull request #2658
Opened 2022-08-10 19:27 UTC by notjosh

Hiya 👋  This is likely somewhat incomplete, as I'm really only focusing on fixing VSCode. If there's more to do for other packages, let me know!

This PR bumps `ts-node` to 10.x, so that TypeScript based configs (i.e. `.graphqlrc.ts`) will continue to work.

## Background

Before this upgrade, the following appeared in my logs:

```8/10/2022, 9:23:24 PM [1] (pid: 8154) graphql-language-service-usage-logs: WARNING: graphql-config error, only highlighting is enabled:
Failed to compile TypeScript: Debug Failure. False expression: Non-string value passed to `ts.resolveTypeReferenceDirective`, likely by a wrapping package working with an outdated `resolveTypeReferenceDirectives` signature. This is probably not a problem in TS itself.
for more information on using 'graphql-config' with 'graphql-language-service-server', 
see the documentation at https://www.npmjs.com/package/graphql-language-service-server#user-content-graphql-configuration-file
```

Other folks online (i.e. [here](https://stackoverflow.com/questions/72488958/false-expression-non-string-value-passed-to-ts-resolvetypereferencedirective)) mentioned that `ts-node` needed updating to resolve this error.

2022-08-10 19:28 UTC, notjosh commented on packages/vscode-graphql/esbuild.js
> +    './transpilers/swc.js', // suppresses warning via ts-node, but we won't be using it, so we can exclude it
The warning was:

```
$ node esbuild
▲ [WARNING] "./transpilers/swc.js" should be marked as external for use with "require.resolve" [require-resolve-not-external]

    ../../node_modules/ts-node/dist/index.js:192:37:
      192 │         transpiler = require.resolve('./transpilers/swc.js');
          ╵                                      ~~~~~~~~~~~~~~~~~~~~~~

{
  detail: undefined,
  id: 'require-resolve-not-external',
  location: {
    column: 37,
    file: '../../node_modules/ts-node/dist/index.js',
    length: 22,
    line: 192,
    lineText: "        transpiler = require.resolve('./transpilers/swc.js');",
    namespace: '',
    suggestion: ''
  },
  notes: [],
```

2022-08-10 19:43 UTC, acao commented
Thank you! This appears to be an issue with the cosmic config plugin for typescript  I added to graphql-config. 

The resolution pin is important to fix an even larger bug. 

Is this working with remote introspection? We had to pin the version just last week because graphql-config‘s undici usage was breaking vscode graphql for even more users!

i generally prefer to not add dependencies that we don’t import to resolve an issue, because these can lead to issues later on

IMHO, we should be fixing the issue in graphql-config‘s resolution of the cosmicconfig plugin or the plugin itself

2022-08-10 19:49 UTC, acao commented
When i tried this fix last week, i got the jest mocks working with the latest whatwg fetch replacement they used in graphql tools url loader, but schema introspection still failed, so I rolled it back & pinned. I would link to the PR but I am on my phone & headed to sleep, so I will check in tomorrow or possibly later if this dependency drift keeps me up another night again 😂😭

2022-08-11 04:47 UTC, acao commented
@notjosh did you confirm this works for url schemas yet? I won’t have time to test the schema changes locally until after work in 10 hours

2022-08-11 06:00 UTC, acao commented
It appears to fix the issue for typescript files, but schema-as-url context appears to be failing silently, I can't get it to work at all with rick & morty API, whereas I was able to before off `main` before checking out this PR. I will look into it some more and see if we can at least get the error to surface. Last week when I tried upgrading `graphql-config` to the latest, to this same version in fact, the schema fetch failure was very visible, now this what appears to be a silent schema fetch failure is even more worrisome! It must be there was another patch version of `@graphql-tools/url-loader`

2022-08-11 06:02 UTC, acao requested changes
Let's confirm that we can get this working in schema-as-url mode first. I can not get a schema introspection fetch to succeed from the LSP server in `vscode-graphql` after this change 😟 !

2022-08-11 06:05 UTC, acao commented on packages/graphql-language-service/package.json
> -    "ts-node": "^8.10.2",
wait.... how did we end up with this dependency in the first place? I think it was added by the GSOC intern who added the benchmarks. It's unfortunate that dev dependency resolutions like this impact the whole build just for a benchmark suite!

2022-08-11 09:20 UTC, notjosh commented
> @notjosh did you confirm this works for url schemas yet? I won’t have time to test the changes locally until after work in 10 hours

Ah, sorry, it was end of day for me yesterday. I'll noodle around a bit with it through the day and see what I can figure out. Seems like we'll need to find the ✨Goldilocks✨ combination of dependencies to cover all the use cases.

2022-08-11 09:41 UTC, notjosh commented
Hrm, it seems to be working okay for me, as far as I can tell.

I created a small sample project with a schema via URL, and a single document (a basic query). When I force the GraphQL LSP to restart, it takes a moment to resolve, but seems to handle the introspection (and therefore autocompletion) just fine:

<img width="1487" alt="image" src="https://user-images.githubusercontent.com/33126/184105895-b10a1638-f469-4eba-82b5-7035d75bbabd.png">

But it's possible I'm missing something entirely, and there's a better way to tell if the introspection is actually working as expected (vs somehow using a cached version after failing). Any thoughts?

2022-08-11 11:25 UTC, acao commented
@notjosh indeed sounds like it's working fine then! false negative on my side. thanks for checking! we're progressively quieting the logs by default to only useful errors and warnings (still a few to go as you can see), so the usual fountain of output for normal language features isn't there by default unless you enable debug mode

2022-08-11 11:30 UTC, acao approved these changes

2022-08-11 11:30 UTC, merged

2022-08-11 20:33 UTC, acao commented
@notjosh published earlier, forgot to mention

I'm noticing @divyenduz 's original `vscode-graphql` package.json had pinned `dependencies` and I think I understand why. ^ versions when you're shipping shared libraries work pretty great. But for end consuming clients that have to ship a fixed bundle? And can't benefit from patch updates? Pin the `dependencies` to reduce the unnecessary surprises 😬 😆 !

2022-08-11 22:05 UTC, acao commented
Ok looks like we need to revert this. Last week repeating itself haha

2022-08-11 22:39 UTC, acao commented
@notjosh can you open a ticket for this bug now that it's been re-introduced?