Add user facing setting for persisting headers
graphql/graphiql pull request #2895
Opened 2022-11-11 21:04 UTC by TheMightyPenguin

# Description

Adds a user control in the settings dialog for persisting headers. This is only visible if the `shouldPersistHeaders` is not passed to the GraphQL component.

Demo and brief explanation: https://www.loom.com/share/b958369673eb4ecbafcd2d1fe1fa0fe9

I also found 2 potential issues when working on this:
- https://github.com/graphql/graphiql/issues/2891 (Accessibility related, I'll give it a shot once this one is completed)
- https://github.com/graphql/graphiql/issues/2892

### Questions
As headers are not persisted as a security measure, should we include a warning for the user in the dialog?

2022-11-12 13:33 UTC, acao commented
thank you so much for this @TheMightyPenguin !

2022-11-12 13:35 UTC, acao commented
> should we include a warning for the user in the dialog?
I think so, perhaps just a warning to make sure they trust the device they are persisting these secrets to.

> do we also need to do the same for tabs state?
it would be lovely if you could cover that case as well!

2022-11-13 10:37 UTC, acao commented
@TheMightyPenguin merged an upstream PR where @jonathanawesome fixed the `act()` issue, sorry for the merge conflicts!

2022-11-13 10:40 UTC, acao commented
> This is only visible if the `shouldPersistHeaders` is not passed to the GraphQL component.

This seems like a sensible choice, however - what if this prop just determines the default value, and the user can choose to override it?

2022-11-14 15:19 UTC, TheMightyPenguin commented
> > This is only visible if the `shouldPersistHeaders` is not passed to the GraphQL component.
> 
> this seems sensible! what do you think of this?
> 
> * if `shouldPersistHeaders` is`false` explicitly, we should not show the setting
> * otherwise, if it is `true` or not specified, the user defined setting is available, defaulting to enabled/disabled respectively

I like it, seems considerate with the end user being in control of their privacy, I'll include this logic in the next commit!

2022-11-18 21:46 UTC, TheMightyPenguin commented
@acao updated PR, now we only show the setting if the property is not set (`undefined`) or `true`, and when it's set to false we also clean up the tabs storage, removing any headers key in there, I added tests for this logic.

I also added a warning message (using the warning color, let me know is the styling is not right 😅):
<img width="716" alt="image" src="https://user-images.githubusercontent.com/11748696/202808277-b4429ba2-64e8-464f-8865-b3d086c16bc1.png">

2022-11-25 11:01 UTC, thomasheyenbrock requested changes
I'm not sure if we should add the state for user-controlling this setting to the `EditorContextProvider`. I feel that this is more of a thing that should happen in user-land (from the perspective of `@graphiql/react`).

To give an example: If I'm building my own custom GraphQL IDE with the components from `@graphiql/react`, I might have a clear opinion on how I want to persist headers or not. I already have the `shouldPersistHeaders` prop that I can use to control this behavior. Changing this state with the `setShouldPersistHeaders` method added in this PR gives me too much control that I don't need.

My proposal here is to move the state for the new toggle button in the settings dialog to the `GraphiQL` component. This component can combine this state with the value it receives as `shouldPersistHeaders` prop and pass the "final" value for that prop to the `GraphiQLProvider`. It also passes the value and the state-setter down to the `GraphiQLInterface` component which will use it to render the toggle button in the settings dialog. That way we don't need to expose any more state or methods from the `EditorContext` which keep it more easy to use.

Finally: Having a chunk of logic in the `EditorContextProvider` that clears the persisted header state when the `shouldPersistHeaders` prop changes is a fantastic addition, so we should definitely leave that in! (In fact, I would even consider it a bug that we're not doing it yet.)

2022-11-25 22:22 UTC, TheMightyPenguin commented
> I'm not sure if we should add the state for user-controlling this setting to the `EditorContextProvider`. I feel that this is more of a thing that should happen in user-land (from the perspective of `@graphiql/react`).
> 
> To give an example: If I'm building my own custom GraphQL IDE with the components from `@graphiql/react`, I might have a clear opinion on how I want to persist headers or not. I already have the `shouldPersistHeaders` prop that I can use to control this behavior. Changing this state with the `setShouldPersistHeaders` method added in this PR gives me too much control that I don't need.
> 
> My proposal here is to move the state for the new toggle button in the settings dialog to the `GraphiQL` component. This component can combine this state with the value it receives as `shouldPersistHeaders` prop and pass the "final" value for that prop to the `GraphiQLProvider`. It also passes the value and the state-setter down to the `GraphiQLInterface` component which will use it to render the toggle button in the settings dialog. That way we don't need to expose any more state or methods from the `EditorContext` which keep it more easy to use.
> 
> Finally: Having a chunk of logic in the `EditorContextProvider` that clears the persisted header state when the `shouldPersistHeaders` prop changes is a fantastic addition, so we should definitely leave that in! (In fact, I would even consider it a bug that we're not doing it yet.)

@thomasheyenbrock I tried implementing this, but there's an issue as the `GraphiQL` would not have access to the storage context. We could make this work somehow but not sure how clean the solution would be 😅. Gonna think this one a bit more to see what workaround we could use.

Additionally, I'd say we could always show the setting in the GraphiQL component, removing the logic we have for showing this in only certain scenarios (e.g. when the prop is `true` or `undefined`) would simplify the code.

2022-11-29 16:43 UTC, TheMightyPenguin commented
@acao @thomasheyenbrock pushed a few commits addressing the comments!

2022-12-02 20:05 UTC, acao approved these changes
Everything looks in order to me, and I concur with your choice to make the option always available!

2022-12-06 20:18 UTC, jonathanawesome commented
Looks good to me, thanks @TheMightyPenguin for the thorough PR!

2022-12-06 20:18 UTC, jonathanawesome approved these changes

2022-12-15 20:15 UTC, TheMightyPenguin commented
@acao @thomasheyenbrock @jonathanawesome anything missing from my side in this PR? (just making sure I am not blocking anything)

2023-01-09 19:02 UTC, thomasheyenbrock approved these changes
Awesome, this looks fine for me 💯

2023-01-09 19:02 UTC, merged