1620: added customize options for some panels
graphql/graphiql pull request #2929
Opened 2022-12-01 16:18 UTC by lasmil

- closes https://github.com/graphql/graphiql/issues/1620

- added the ability to hide/show the 'second panel'
- added the ability to hide/show just the 'editor panel' (inside second panel)
- added the ability to hide/show just the 'results panel' (inside second panel)
- added the ability to apply custom styles to the 'second panel' container
- added the ability to apply custom styles to the 'editor panel' container
- added the ability to apply custom styles to the 'results panel' container

I checked how the hiding of these panels would work and I noticed that the best option to implement the feature is using the 'display' CSS property when would like to hide the specific panel. The reason behind this is that the panel 'ref' does some calculations when the page is loaded. These are lost if we are "react" removing the panel, ie using the
`{ !hideSecondPanel && <div> ... </div> `}
syntax. Toggling the "displayness (display: none to flex)" fixes this issue and if we conditionally toggle these panels visibility, everything would work as it should.

I added separate optional properties related to styling. In this way, the user won't be confused when trying to use them.

Backward compatibility is provided, hence these new props are optional.

2022-12-01 16:59 UTC, TallTed commented on .changeset/rich-lamps-beg.md
> +- results panel - with the `hideResultsPanel` prop
```suggestion
1) Added optional props which can be used to toggle the visibility of
   - second panel — with the `hideSecondPanel` prop
   - editor panel — with the `hideEditorPanel` prop
   - results panel — with the `hideResultsPanel` prop
```

2022-12-01 16:59 UTC, TallTed commented on .changeset/rich-lamps-beg.md
> +- results panel - with the `resultsPanelStyle` prop
```suggestion
   - second panel — with the `secondPanelStyle` prop
   - editor panel — with the `editorPanelStyle` prop
   - results panel — with the `resultsPanelStyle` prop
```

2022-12-01 17:00 UTC, TallTed commented on packages/graphiql/src/components/GraphiQL.tsx
> +     * Toggle if editor panel should be shown.
```suggestion
     * Toggle if the editor panel should be shown.
```

2022-12-01 17:14 UTC, acao commented
@thomasheyenbrock and @jonathanawesome would you agree that this change should come along with:

1. overriding plugins with `plugins` prop
2. deprecating other props for hiding/disabling panes

another thought here @lasmil  - we are trying to use css classes for overriding styles more at this point  - I'll defer to my colleauges whether this new pattern of passing raw css-in-js props is what they had in mind

2022-12-01 17:33 UTC, simoneb commented
This contribution is being made by NearForm. We're working on the CLA.

2022-12-01 17:34 UTC, lasmil commented
> @thomasheyenbrock and @jonathanawesome would you agree that this change should come along with:
> 
> 1. overriding plugins with `plugins` prop
> 2. deprecating other props for hiding/disabling panes
> 
> another thought here @lasmil - we are trying to use css classes for overriding styles more at this point - I'll defer to my colleauges whether this new pattern of passing raw css-in-js props is what they had in mind

Sure thing. I can work with both options. I went with this option though because it was one of the easiest way to keep backward compatibility and also keep certain already present style values.
If you choose to go with css classes then I can either try to update this PR accordingly or we can create another issue for future reference.

We need this functionality in one of our repos, thus I ended up going with the easiest solution.

2022-12-01 19:01 UTC, jonathanawesome commented
Hey there @lasmil & @simoneb, thanks for the PR!

I'm not against expanding the API surface of `GraphiQLInterfaceProps`, especially if they're optional and tested, but I do think that an effort should be made to work within the convention of using class names for styling overrides. If adding class names to the target divs can get you folks the functionality you're after, that should be the way forward.

There was consideration early on in the new design that had an alternative view for plugins that needed more space and didn't need to interface directly with the editor(s):
<img width="735" alt="Screen Shot 2022-12-01 at 12 45 41 PM" src="https://user-images.githubusercontent.com/963528/205136830-23d8bcb2-7491-4b03-9337-11e54b5ba0a8.png">

Outside of more general discussions around enhancing the plugin API, we haven't discussed specifically how this might work, though I wonder if this view might be a better fit for the plugin you're building. If so, we should take the opportunity to discuss!

2022-12-01 20:50 UTC, lasmil commented
> Hey there @lasmil & @simoneb, thanks for the PR!
> 
> I'm not against expanding the API surface of `GraphiQLInterfaceProps`, especially if they're optional and tested, but I do think that an effort should be made to work within the convention of using class names for styling overrides. If adding class names to the target divs can get you folks the functionality you're after, that should be the way forward.
> 
> There was consideration early on in the new design that had an alternative view for plugins that needed more space and didn't need to interface directly with the editor(s): <img alt="Screen Shot 2022-12-01 at 12 45 41 PM" width="735" src="https://user-images.githubusercontent.com/963528/205136830-23d8bcb2-7491-4b03-9337-11e54b5ba0a8.png">
> 
> Outside of more general discussions around enhancing the plugin API, we haven't discussed specifically how this might work, though I wonder if this view might be a better fit for the plugin you're building. If so, we should take the opportunity to discuss!

Alright, I will see what can we do with the class names. 
The plugin we are building requires the entire second panel to be hidden, so I have taken this task to make the inner panels configurable as well.

2022-12-01 21:41 UTC, acao commented
@lasmil though these props will definitely be useful to users, especially dynamically - for your project in particular, you may find yourself limited in overriding layout, styling approach, etc as a whole - if so, consider just using `@graphiql/react` and `@graphiql/toolkit` directly?

`graphiql` itself is now one big layout component. It's meant to be a starting point for more complex use cases, then you can cut out/replace half the UI as needed, and still be able to use plugins if you import their CSS
https://github.com/graphql/graphiql/blob/main/packages/graphiql/src/components/GraphiQL.tsx

`@graphiql/react` components forward their refs so you can apply whatever css-in-js approach you like.

2022-12-01 21:50 UTC, lasmil commented
> @lasmil [Here's a sandbox](https://codesandbox.io/s/graphiql-full-view-plugin-eigzsu) that may be helpful!
> 
> Also, I'm on the [discord](https://discord.com/channels/625400653321076807/862957469155721236) if you'd like to chat.

Ohh I see what you did there. Alright, for our plugin, this can work and then we don't really need any of these changes.
Nevertheless we may keep these changes as well which can be useful in some scenarios as @acao mentioned.

2022-12-01 23:16 UTC, lasmil commented
PR updated with using class names instead of style objects.

2023-03-31 12:36 UTC, thomasheyenbrock requested changes
Hey @lasmil 👋 thanks for the PR! There hasn't been a lot of activity here for a while, is the PR still relevant / up-to-date?

I have to admit, I'm not fond of adding a bunch of new props. It makes the API surface even more complex (it's already huge) and just harder to maintain in the long run.

GraphiQL is meant to be the reference implementation for a GraphQL IDE, and I see all panels as an essential part of that. Of course there is a good use-case for hiding one or the other, but there's good use-cases for a lot of things. That's also why we published `@graphiql/react` to enable everybody to build their own GraphQL IDEs with their own custom behavior.

Instead of having props for this, I could also imagine adding a simple `display: none` to the DOM elements that wrap the respective panels in user land. Would that also be a viable solution?

2023-07-05 20:59 UTC, closed without merging