fix: html examples
graphql/graphiql pull request #3097
Opened 2023-03-10 20:43 UTC by chenaski

I tried to use `packages/graphiql-plugin-code-exporter/examples/index.html` and `packages/graphiql-plugin-explorer/examples/index.html` examples, but it turned out that they don't work.

- Updated integrity attribute of `https://unpkg.com/graphiql/graphiql.min.js`
- Added `regenerator-runtime` script in `graphiql-plugin-code-exporter`

2023-03-20 13:27 UTC, acao commented
thank you for this @chenaski ! hard to keep these examples working, so many to keep track of, no automatic validation

2023-04-05 19:34 UTC, chenaski commented
Yeah, I can understand. Actually I was thinking about writing some tests to check if HTMLs open without errors, but it takes time, so at least this will fix them for now.

2023-04-14 15:15 UTC, thomasheyenbrock requested changes
Seems like the integrity hashes are outdated yet again 😓 
<img width="577" alt="CleanShot 2023-04-14 at 17 13 42@2x" src="https://user-images.githubusercontent.com/22288634/232084364-f297fc9e-14e7-47a2-9d45-070cb7d2d34e.png">

2023-04-21 08:53 UTC, chenaski commented
Updated them again :)

2023-06-01 22:35 UTC, B2o5T commented
`integrity` was removed with update all examples to React 18 here https://github.com/graphql/graphiql/pull/3185/files

2023-06-01 22:35 UTC, closed without merging

2023-06-02 07:45 UTC, thomasheyenbrock commented
@B2o5T makes sense, as we don't have a way to automatically update these hashes on releases, it's just too much overhead at the moment. Thanks @chenaski!