Updated cm6-graphql package README
graphql/graphiql pull request #3127
Opened 2023-04-03 00:06 UTC by imolorhe

Updated cm6-graphql package README

2023-04-03 17:58 UTC, TallTed requested changes
Fix some capitalization

2023-04-03 17:58 UTC, TallTed commented on packages/cm6-graphql/README.md
> +Note: You have to provide a theme to codemirror 6 for the styling you want. You can take a look at [this example](https://github.com/graphql/graphiql/blob/main/examples/cm6-graphql-parcel/src/index.t
```suggestion
Note: You have to provide a theme to CodeMirror 6 for the styling you want. You can take a look at [this example](https://github.com/graphql/graphiql/blob/main/examples/cm6-graphql-parcel/src/index.ts) or see the CodeMirror 6 [documentation examples](https://codemirror.net/examples/styling/) for more details.
```

2023-04-04 10:55 UTC, acao commented
thank you @imolorhe ! just need to run `yarn pretty` to make prettier happier about the markdown

one other thing while we're here, can we add a section at the beginning of the `codemirror-graphql` readme that says something like "for codemirror 6 support, use cm6-graphql" with a link?

2023-04-06 16:03 UTC, TallTed requested changes

2023-04-06 16:03 UTC, TallTed commented on packages/cm6-graphql/README.md
> +details.
```suggestion
_**Note:** You have to provide a theme to CodeMirror 6 for the styling you want. You
can take a look at
[this example](https://github.com/graphql/graphiql/blob/main/examples/cm6-graphql-parcel/src/index.ts)
or see the CodeMirror 6
[documentation examples](https://codemirror.net/examples/styling/) for more
details._
```

2023-04-06 16:03 UTC, TallTed commented on packages/cm6-graphql/README.md
> +If you need to update the GraphQL schema used in the editor dynamically, you can
```suggestion
If you need to dynamically update the GraphQL schema used in the editor, you can
```

2023-04-07 13:39 UTC, acao approved these changes
awesome work!

2023-04-07 13:40 UTC, merged

2023-04-07 16:04 UTC, TallTed commented
@acao — You merged without you or @imolorhe applying or even commenting on [my suggested changes](https://github.com/graphql/graphiql/pull/3127#pullrequestreview-1375167866). Why?

2023-05-12 20:33 UTC, TallTed commented
I've taken my other suggestions to #3174