GraphiQL component: `showThemeSettings`
graphql/graphiql pull request #3407
Opened 2023-08-22 12:14 UTC by TuvalSimha

2023-08-23 09:32 UTC, B2o5T requested changes
> Can enforce the theme from editorTheme prop.

so if the user can enforce the theme via `editorTheme` why do we need additional prop `showThemeSettings`?

We could show the theme toggle only if `props.editorTheme` was not set

Also please add simple cypress tests

2023-08-23 11:26 UTC, TuvalSimha commented
But if you want to implement you theme, but still give users the option
change the theme, how you can do it?

On Wed, 23 Aug 2023 at 12:32 Dimitri POSTOLOV ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Can enforce the theme from editorTheme prop.
>
> so if the user can enforce the theme via editorTheme why do we need
> additional prop showThemeSettings?
>
> We could show the theme toggle only if props.editorTheme was not set
>
> Also please add simple cypress tests
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/graphql/graphiql/pull/3407#pullrequestreview-1591168806>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI67K7YZRDN2CBHQQ52J22TXWXEZXANCNFSM6AAAAAA3Z2G3YQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-23 21:32 UTC, mvdiener commented
Hello, I'm not an active contributor to this repo, but I am actively watching these changes because I'm very interested in utilizing this property.

I'm wondering if these changes still allow for the utilization of the system theme? In the code for the `useTheme` [hook](https://github.com/graphql/graphiql/blob/main/packages/graphiql-react/src/theme.ts#L10), the theme value of null indicates the theme should use the system default. Does the new `forcedTheme` property allow for the scenario where we want to hide the theme toggle in the settings modal, but also want the theme to be set based on the system default?

Perhaps a third option for theme: `forcedTheme?: 'light' | 'dark' | 'system';` and under the hood, 'system' can be translated to null when calling `setTheme()`?

Thank you, and looking forward to these upcoming changes!

2023-08-24 01:17 UTC, B2o5T commented
@mvdiener i guess we can use `undefined` value to disable `forcedTheme` and `null` to set as theme `system` and migrate to next-themes package in v4 which has `system` that is aka `null` now (in our useTheme hook)

2023-08-27 14:27 UTC, B2o5T commented on packages/graphiql/cypress/e2e/theme.cy.ts
> +    cy.visit('/?query={test}&forceTheme=light');
```suggestion
    cy.visit('/?query={test}&forcedTheme=light');
```

2023-08-27 14:27 UTC, B2o5T commented on packages/graphiql/cypress/e2e/theme.cy.ts
> +  it('Switches to light theme when forceTheme is light', () => {
```suggestion
  it('Switches to light theme when forcedTheme is light', () => {
```

2023-08-27 14:28 UTC, B2o5T commented on packages/graphiql/cypress/e2e/theme.cy.ts
> +    cy.visit('/?query={test}&forceTheme=dark');
```suggestion
  it('Switches to dark theme when forcedTheme is dark', () => {
    cy.visit('/?query={test}&forcedTheme=dark');
```

2023-08-27 14:28 UTC, B2o5T commented on packages/graphiql/cypress/e2e/theme.cy.ts
> +    cy.visit('/?query={test}&forceTheme=invalid');
```suggestion
  it('Defaults to light theme when forcedTheme value is invalid', () => {
    cy.visit('/?query={test}&forcedTheme=invalid');
```

2023-08-27 14:28 UTC, B2o5T commented on packages/graphiql/resources/renderExample.js
> +    forceTheme: parameters.forceTheme,
```suggestion
    forcedTheme: parameters.forcedTheme,
```

2023-08-27 14:28 UTC, B2o5T commented on packages/graphiql/src/components/GraphiQL.tsx
> +     * rendered with a specific theme, even if the user has a different
```suggestion
     * rendered with a specific theme
```

2023-08-27 14:29 UTC, B2o5T commented on packages/graphiql/src/components/GraphiQL.tsx
> +          {props.forcedTheme ? null : (
```suggestion
          {!props.forcedTheme && (
```

2023-08-27 14:32 UTC, B2o5T commented on .changeset/famous-shirts-mate.md
> +Create new prop to GraphiQL component: `forcedTheme` to control the theme.
```suggestion
Add a new prop to GraphiQL component: `forcedTheme` to force the theme and hide the theme switcher.
```

2023-08-27 14:32 UTC, B2o5T commented on packages/graphiql/cypress/e2e/theme.cy.ts
> +    cy.get('body').should('have.class', 'graphiql-light'); // Check for the class indicating light theme
```suggestion
    cy.get('body').should('have.class', 'graphiql-light');
```

2023-08-27 14:32 UTC, B2o5T commented on packages/graphiql/cypress/e2e/theme.cy.ts
> +    cy.get('body').should('have.class', 'graphiql-dark'); // Check for the class indicating dark theme
```suggestion
    cy.get('body').should('have.class', 'graphiql-dark');
```

2023-08-27 14:32 UTC, B2o5T commented on packages/graphiql/cypress/e2e/theme.cy.ts
> +    cy.get('body').should('have.class', 'graphiql-light'); // Check for the class indicating light theme
```suggestion
    cy.get('body').should('have.class', 'graphiql-light');
```

2023-10-06 05:03 UTC, louisscruz commented
Are there any additional adjustments needed to get this in? cc @B2o5T

2023-10-11 19:12 UTC, TallTed commented on packages/graphiql/src/components/GraphiQL.tsx
> +     * forcedTheme allows to enforce a specific theme for GraphiQL.
```suggestion
     * forcedTheme allows enforcement of a specific theme for GraphiQL.
```

2023-10-11 19:18 UTC, TallTed commented on packages/graphiql/src/components/GraphiQL.tsx
> +                  Adjust how the interface looks like.
```suggestion
                  Adjust how the interface appears.
```

2024-06-17 14:32 UTC, dimaMachina approved these changes

2024-06-17 14:33 UTC, merged