test after coverage for recent features/changes 😬
graphql/graphiql pull request #3521
Opened 2024-01-27 15:14 UTC by acao

this should also fix crash on editing `package.json`

2024-03-04 01:34 UTC, acao commented
For anyone who wants to give it a try, here is a zip of the 0.10.0 vsix!
[vscode-bugfixes.zip](https://github.com/graphql/graphiql/files/14475534/vscode-bugfixes.zip)

2024-03-04 15:47 UTC, TallTed requested changes
small, human-facing

2024-03-04 15:47 UTC, TallTed commented on .changeset/rotten-seahorses-fry.md
> +this fixes multiple cacheing bugs, on writing some in-depth integration coverage for the LSP server.
```suggestion
this fixes multiple caching bugs, on writing some in-depth integration coverage for the LSP server.
```

2024-03-04 15:47 UTC, TallTed commented on .changeset/rotten-seahorses-fry.md
> +Fix many schema and fragment lifecycle issues, for all contexts except for schema updates for url schemas.
```suggestion
Fix many schema and fragment lifecycle issues, for all contexts except schema updates of url schemas.
```

2024-03-04 15:47 UTC, TallTed commented on .changeset/rotten-seahorses-fry.md
> +- **total increased test coverage of about 25% in the LSP server codebase.**
```suggestion
- **total increased test coverage of about 25% in the LSP server codebase**
```

2024-04-08 14:49 UTC, TallTed commented on packages/graphql-language-service-server/src/MessageProcessor.ts
> +    // because sdlOnly needs this file to be removed as well if the user is switching schemas
```suggestion
    // because sdlOnly also needs this file to be removed, if the user is switching schemas
```

2024-04-08 14:52 UTC, TallTed commented on packages/vscode-graphql/README.md
> +There are a number of configurations that can be provided from both editor settings or the graphql config file, and the editor setting takes precedence, to allow users to override their graphql confi
```suggestion
There are a number of configurations that can be provided from editor settings and/or the graphql config file, with the editor settings taking precedence, so users can override their graphql config file settings in a user context, as needed.
```

2024-04-08 14:53 UTC, TallTed commented on packages/vscode-graphql/package.json
> +          "description": "Schema cache ttl in milliseconds before requesting a fresh schema when caching the local schema file is enabled. Defaults to 30000 (30 seconds).",
```suggestion
          "description": "Schema cache ttl, in milliseconds before requesting a fresh schema when caching the local schema file is enabled. Defaults to 30000 (30 seconds).",
```

2024-05-28 06:27 UTC, merged